from enum import Enum, auto


class TokenTypes(Enum):
    EOT = auto()
    IDENTIFIER = auto()
    NUMBER = auto()
    DECIMAL = auto()
    CURRENCY = auto()
    STRING = auto()
    PLUS = auto()
    MINUS = auto()
    MULTIPLY = auto()
    DIVIDE = auto()
    OP_BRACKET = auto()
    CL_BRACKET = auto()
    OP_CURLY_BRACKET = auto()
    CL_CURLY_BRACKET = auto()
    OP_SQUARE_BRACKET = auto()
    CL_SQUARE_BRACKET = auto()
    SEMICOLON = auto()
    DOT = auto()
    COMMA = auto()
    NOT = auto()
    IF = auto()
    ELSE = auto()
    WHILE = auto()
    RETURN = auto()
    LESS_THAN = auto()
    GREATER_THAN = auto()
    LESS_OR_EQUAL = auto()
    GREATER_OR_EQUAL = auto()
    ASSIGNMENT = auto()
    EQUAL = auto()
    NOT_EQUAL = auto()
    AND = auto()
    OR = auto()
    PRINT = auto()
    GET_CURRENCY = auto()

